<a href="https://colab.research.google.com/github/Andesia/Aflatoxin-Prediction/blob/main/mlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
afla = pd.read_csv("aflapredict.csv")
#print(afla.head())

In [ ]:
df=pd.DataFrame(afla)
df


Relative Humidity  Soil temp.  Soil Wetness  Max temp.  Min temp.  \
0                65.81       17.66          0.41      31.81      12.99   
1                76.25       19.38          0.30      32.83      13.02   
2                75.75       18.67          0.43      32.09      15.44   
3                62.81       17.08          0.70      28.50      14.22   
4                79.94       16.61          0.70      26.47      13.61   
..                 ...         ...           ...        ...        ...   
487              77.06       16.15          0.34      33.50      12.12   
488              74.00       17.91          0.27      32.12      13.03   
489              73.69       18.49          0.33      32.30      13.65   
490              76.81       18.38          0.40      32.26      14.51   
491              84.69       16.66          0.53      29.21      14.76   

     Average temp.  Rainfall  class   
0            21.55      0.00       0  
1            22.74      5.27       1  
2            22.24    131.84       1  
3            20.42    205.66       0  
4            19.44    110.74       0  
..             ...       ...     ...  
487          19.90     15.37       0  
488          21.21      7.75       0  
489          22.36     28.51       0  
490          22.46     54.02       0  
491          20.81    137.37       1  

[492 rows x 8 columns]

In [ ]:
afla.shape

(492, 8)

In [ ]:
afla.describe(include = 'all')

Relative Humidity  Soil temp.  Soil Wetness   Max temp.   Min temp.  \
count         492.000000  492.000000    492.000000  492.000000  492.000000   
mean           76.739736   17.256341      0.454268   30.632724   12.985122   
std             7.273804    1.276898      0.107082    1.781498    1.539400   
min            50.880000   14.300000      0.250000   25.690000    8.410000   
25%            72.690000   16.377500      0.370000   29.350000   11.830000   
50%            78.155000   17.120000      0.460000   30.800000   12.980000   
75%            82.137500   18.050000      0.520000   31.810000   14.142500   
max            89.000000   20.520000      0.860000   35.240000   16.630000   

       Average temp.    Rainfall      class   
count     492.000000  492.000000  492.000000  
mean       20.837053   47.341057    0.276423  
std         1.249073   55.188723    0.447684  
min        18.140000    0.000000    0.000000  
25%        19.880000    5.270000    0.000000  
50%        20.815000   26.370000    0.000000  
75%        21.692500   73.830000    1.000000  
max        24.660000  279.490000    1.000000

In [ ]:
X = df.iloc[:, :-1].values  #features
print(X)

[[ 65.81  17.66   0.41 ...  12.99  21.55   0.  ]
 [ 76.25  19.38   0.3  ...  13.02  22.74   5.27]
 [ 75.75  18.67   0.43 ...  15.44  22.24 131.84]
 ...
 [ 73.69  18.49   0.33 ...  13.65  22.36  28.51]
 [ 76.81  18.38   0.4  ...  14.51  22.46  54.02]
 [ 84.69  16.66   0.53 ...  14.76  20.81 137.37]]


In [ ]:
y = df.iloc[:, -1].values  #target
print(y)

[0 1 1 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0
 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0
 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 0
 0 0 0 0 0 1 0 0 0 1 1 1 1 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0
 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0
 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0
 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0
 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1
 1 0 0 0 0 1 1 1 1 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 1 1 0 1 0 0 0 1 0 1 0 0 1 1 1 1 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 1 0
 0 0 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0
 0 0 1 1 0 0 0 0 0 0 1]


**Splitting to training and testing**


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

print(X_train.shape)
print(y_test.shape)

(344, 7)
(148,)


Normalized input X train

**Train the model**

Import the MLP classifier model from sklearn

In [ ]:
from sklearn.neural_network import MLPClassifier

In [ ]:
mlp = MLPClassifier(hidden_layer_sizes=(3, 2), max_iter=500, activation='relu')
mlp

MLPClassifier(hidden_layer_sizes=(3, 2), max_iter=500)

**About parameters**

**Training**

In [ ]:
mlp.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(3, 2), max_iter=500)

**Testing**

In [ ]:
pred = mlp.predict(X_test)
pred

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0])

**Evaluation Metrics- Confusion Matrix and F2 Score**

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

confusion_matrix(y_test, pred)

array([[104,   8],
       [ 26,  10]])

In [ ]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.80      0.93      0.86       112
           1       0.56      0.28      0.37        36

    accuracy                           0.77       148
   macro avg       0.68      0.60      0.61       148
weighted avg       0.74      0.77      0.74       148

